eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka-server-production.up.railway.app/eureka
  
spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: https://evaluation-microservice-production.up.railway.app/
          predicates:
            - Path= /evaluation/**
        - id: r2
          uri: https://booking-microservice-production.up.railway.app/
          predicates:
            - Path= /announcements/**
